# Generated by Django 2.1 on 2018-12-06 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complain_o_citizen_2000', '0003_minicomplaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigcomplaint',
            name='user',
        ),
        migrations.RemoveField(
            model_name='minicomplaint',
            name='bigcomplaint',
        ),
        migrations.RemoveField(
            model_name='minicomplaint',
            name='user',
        ),
        migrations.DeleteModel(
            name='BigComplaint',
        ),
        migrations.DeleteModel(
            name='MiniComplaint',
        ),
    ]
