# Generated by Django 2.1 on 2018-12-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_o_citizen_2000', '0005_bigcomplaint_minicomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigcomplaint',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bigcomplaint',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
