# Generated by Django 2.1 on 2018-12-07 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_o_citizen_2000', '0006_auto_20181207_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigcomplaint',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
