# Generated by Django 2.1 on 2018-12-07 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain_o_citizen_2000', '0007_bigcomplaint_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='minicomplaint',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
